# Generated by Django 2.2.7 on 2019-12-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0012_dron_numero_motores'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='modelo',
            field=models.CharField(default='', max_length=400),
        ),
    ]
